// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMnb6VFzOg1VpZDYNzAYa9jCeIAE_BmUA',
    appId: '1:596336999450:web:64ac2ddb5d22121e3965a3',
    messagingSenderId: '596336999450',
    projectId: 'todotask01-72231',
    authDomain: 'todotask01-72231.firebaseapp.com',
    storageBucket: 'todotask01-72231.appspot.com',
    measurementId: 'G-494X2KV6M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUmGPvgdadBnILyvDxrcmZG67GT3iEP-Q',
    appId: '1:596336999450:android:66290f467b8f04c73965a3',
    messagingSenderId: '596336999450',
    projectId: 'todotask01-72231',
    storageBucket: 'todotask01-72231.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAORUpsNwSHb2OgqgSStyrsuIdPnX-VkEs',
    appId: '1:596336999450:ios:4964a00c63f985273965a3',
    messagingSenderId: '596336999450',
    projectId: 'todotask01-72231',
    storageBucket: 'todotask01-72231.appspot.com',
    iosBundleId: 'com.example.todotask01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAORUpsNwSHb2OgqgSStyrsuIdPnX-VkEs',
    appId: '1:596336999450:ios:4964a00c63f985273965a3',
    messagingSenderId: '596336999450',
    projectId: 'todotask01-72231',
    storageBucket: 'todotask01-72231.appspot.com',
    iosBundleId: 'com.example.todotask01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMnb6VFzOg1VpZDYNzAYa9jCeIAE_BmUA',
    appId: '1:596336999450:web:ef5671d6f9178b7b3965a3',
    messagingSenderId: '596336999450',
    projectId: 'todotask01-72231',
    authDomain: 'todotask01-72231.firebaseapp.com',
    storageBucket: 'todotask01-72231.appspot.com',
    measurementId: 'G-VH90KK4F5B',
  );
}
